### ISSUE TITLE
Install problem message

### ISSUE THREAD

**Issue by Kolenmi** [nanego/redmine_typologies#1]
bitnami@debian:/opt/bitnami/apps/redmine/htdocs/plugins$ sudo bundle exec rake redmine:plugins NAME=redmine_typologies RAILS_ENV=production
(in /opt/bitnami/apps/redmine/htdocs)
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_typologies/lib/models/tracker_patch.rb:8: warning: already initialized constant Tracker::CORE_FIELDS
/opt/bitnami/apps/redmine/htdocs/app/models/tracker.rb:26: warning: previous definition of CORE_FIELDS was here
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_typologies/lib/models/tracker_patch.rb:9: warning: already initialized constant Tracker::CORE_FIELDS_ALL
/opt/bitnami/apps/redmine/htdocs/app/models/tracker.rb:27: warning: previous definition of CORE_FIELDS_ALL was here
== 1 AddTypologyIdToIssues: migrating =========================================
-- add_column(:issues, :typology_id, :integer, {:default=>nil})
   -> 0.7326s
-- add_index(:issues, :typology_id)
   -> 0.1586s
== 1 AddTypologyIdToIssues: migrated (0.8918s) ================================

== 2 CreateProjectTypologiesTable: migrating ==================================
-- create_table(:project_typologies)
   -> 0.1742s
-- add_index(:project_typologies, [:project_id, :typology_id], {:unique=>true, :name=>:projects_typologies_ids})
   -> 0.1701s
== 2 CreateProjectTypologiesTable: migrated (0.3484s) =========================

== 3 CreateProjectTypologiesTrackersTable: migrating ==========================
-- create_table(:project_typologies_trackers, {:id=>false})
   -> 0.2546s
-- remove_column(:project_typologies, :tracker_id, :integer)
   -> 0.3602s
== 3 CreateProjectTypologiesTrackersTable: migrated (0.6156s) =================

**Comment by nanego** [comment]
Hi. I don't see any problem here. Only warnings.
Next time you open an issue, please describe your problem. Logs are not enough.

**Comment by Kolenmi** [comment]
Problem is, after install plugin, Redmine is broken. It does not work. I must uninstall plugin. After that, Redmine is working. I am sorry that log is not enough. I am using "Bitnami Redmine".
Thank you for your response.
